services:
  - type: web
    name: factory-springboot-app
    env: java
    plan: free
    buildCommand: "./gradlew build"
    startCommand: "java -jar build/libs/factory-0.0.1-SNAPSHOT.jar"
    envVars:
      - key: PORT
        value: 8080
